// <auto-generated />
using System;
using CarpetOpsSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarpetOpsSystem.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20260205094247_RenameFabricTypeColumns")]
    partial class RenameFabricTypeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarpetOpsSystem.Models.FabricPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("as_plan");

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode_no");

                    b.Property<string>("CnvDesc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cnv_desc");

                    b.Property<string>("CnvId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cnv_id");

                    b.Property<int?>("ItemNo")
                        .HasColumnType("integer")
                        .HasColumnName("item_no");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("integer")
                        .HasColumnName("layout_id");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<int?>("ListNo")
                        .HasColumnType("integer")
                        .HasColumnName("list_no");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<int?>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<decimal>("Sqm")
                        .HasColumnType("numeric")
                        .HasColumnName("sqm");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNo")
                        .IsUnique();

                    b.HasIndex("CnvId");

                    b.HasIndex("LayoutId");

                    b.HasIndex("OrderNo");

                    b.HasIndex("OrderType");

                    b.ToTable("fabric_pieces");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.FabricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnvDesc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cnv_desc");

                    b.Property<string>("CnvId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cnv_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErpCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("erp_code");

                    b.Property<decimal>("RollWidthM")
                        .HasColumnType("numeric")
                        .HasColumnName("roll_width_m");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("numeric")
                        .HasColumnName("thickness");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CnvId");

                    b.HasIndex("ErpCode")
                        .IsUnique();

                    b.ToTable("fabric_types");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InnerSpacing")
                        .HasColumnType("numeric")
                        .HasColumnName("inner_spacing");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("layout_name");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer")
                        .HasColumnName("order_count");

                    b.Property<decimal>("OuterSpacing")
                        .HasColumnType("numeric")
                        .HasColumnName("outer_spacing");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer")
                        .HasColumnName("piece_count");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("sample_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area_sqm");

                    b.Property<decimal>("TotalLength")
                        .HasColumnType("numeric")
                        .HasColumnName("total_length");

                    b.Property<decimal>("TotalWidth")
                        .HasColumnType("numeric")
                        .HasColumnName("total_width");

                    b.Property<decimal>("UsedAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("used_area_sqm");

                    b.Property<decimal>("WasteAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("waste_area_sqm");

                    b.Property<decimal>("WastePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("waste_percentage");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("layouts");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.LayoutItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("area_sqm");

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode_no");

                    b.Property<bool>("IsRotated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rotated");

                    b.Property<int>("LayoutId")
                        .HasColumnType("integer")
                        .HasColumnName("layout_id");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<decimal>("XPosition")
                        .HasColumnType("numeric")
                        .HasColumnName("x_position");

                    b.Property<decimal>("YPosition")
                        .HasColumnType("numeric")
                        .HasColumnName("y_position");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNo");

                    b.HasIndex("LayoutId");

                    b.HasIndex("LayoutId", "BarcodeNo")
                        .IsUnique()
                        .HasDatabaseName("ix_layout_items_layout_barcode_unique");

                    b.ToTable("layout_items");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnvId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cnv_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InnerSpacing")
                        .HasColumnType("numeric")
                        .HasColumnName("inner_spacing");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer")
                        .HasColumnName("order_count");

                    b.Property<decimal>("OuterSpacing")
                        .HasColumnType("numeric")
                        .HasColumnName("outer_spacing");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer")
                        .HasColumnName("piece_count");

                    b.Property<decimal>("RollWidthM")
                        .HasColumnType("numeric")
                        .HasColumnName("roll_width_m");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area_sqm");

                    b.Property<decimal>("UsedAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("used_area_sqm");

                    b.Property<decimal>("UsedLengthM")
                        .HasColumnType("numeric")
                        .HasColumnName("used_length_m");

                    b.Property<decimal>("UtilizationPct")
                        .HasColumnType("numeric")
                        .HasColumnName("utilization_pct");

                    b.Property<decimal>("WasteAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("waste_area_sqm");

                    b.HasKey("Id");

                    b.HasIndex("CnvId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("plans");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.PlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("area_sqm");

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode_no");

                    b.Property<bool>("IsRotated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rotated");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<decimal>("XPosition")
                        .HasColumnType("numeric")
                        .HasColumnName("x_position");

                    b.Property<decimal>("YPosition")
                        .HasColumnType("numeric")
                        .HasColumnName("y_position");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNo");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanId", "BarcodeNo")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_items_plan_barcode_unique");

                    b.ToTable("plan_items");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.PlanOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnvId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cnv_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer")
                        .HasColumnName("piece_count");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("TotalAreaSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area_sqm");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo");

                    b.HasIndex("PlanId");

                    b.HasIndex("CnvId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_orders_cnv_order_unique");

                    b.ToTable("plan_orders");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.FabricPiece", b =>
                {
                    b.HasOne("CarpetOpsSystem.Models.Layout", "Layout")
                        .WithMany("FabricPieces")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.LayoutItem", b =>
                {
                    b.HasOne("CarpetOpsSystem.Models.Layout", "Layout")
                        .WithMany("Items")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.PlanItem", b =>
                {
                    b.HasOne("CarpetOpsSystem.Models.Plan", "Plan")
                        .WithMany("PlanItems")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.PlanOrder", b =>
                {
                    b.HasOne("CarpetOpsSystem.Models.Plan", "Plan")
                        .WithMany("PlanOrders")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.Layout", b =>
                {
                    b.Navigation("FabricPieces");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("CarpetOpsSystem.Models.Plan", b =>
                {
                    b.Navigation("PlanItems");

                    b.Navigation("PlanOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
